package com.bank.signaturemanagement.service;
import com.bank.signaturemanagement.entity.*;import com.bank.signaturemanagement.repository.*;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;import java.time.LocalDateTime;import java.util.*;
@Service public class EmployeeMediaRequestService{
 private final EmployeeMediaRequestRepository requests;private final EmployeeRepository employees;private final UserRepository users;private final FileStorageService files;private final AccessControlService access;private final AuditService audit;private final SignatureVersionRepository signatures;private final EmployeeMediaVersionRepository mediaVersions;
 public EmployeeMediaRequestService(EmployeeMediaRequestRepository r,EmployeeRepository e,UserRepository u,FileStorageService f,AccessControlService a,AuditService audit,SignatureVersionRepository s,EmployeeMediaVersionRepository mv){requests=r;employees=e;users=u;files=f;access=a;this.audit=audit;signatures=s;mediaVersions=mv;}
 @Transactional public void submit(Long employeeId,MultipartFile photo,MultipartFile local,MultipartFile foreign,String username){if(!access.hasAnyRole(username,"PD","ADMIN"))throw new AccessDeniedException("PD authority is required");Employee e=employees.findById(employeeId).orElseThrow(()->new IllegalArgumentException("Employee not found"));if(requests.existsByEmployeeIdAndStatusIn(employeeId,List.of("PENDING_DGM","PENDING_GM")))throw new IllegalArgumentException("This employee already has a pending media request");boolean p=present(photo),l=present(local),f=present(foreign);if(!p&&!l&&!f)throw new IllegalArgumentException("Upload at least one profile or signature image");if(p&&e.getPhotoPath()!=null)throw new IllegalArgumentException("Existing profile photo changes require an initiated employee update");if(l&&e.getSignaturePath()!=null)throw new IllegalArgumentException("Existing LOCAL signature requires DGM/GM initiation");if(f&&e.getForeignSignaturePath()!=null)throw new IllegalArgumentException("Existing FOREIGN signature requires DGM/GM initiation");EmployeeMediaRequest r=new EmployeeMediaRequest();r.setEmployee(e);r.setSubmittedBy(users.findByUsername(username).orElseThrow());if(p)r.setPhotoPath(store(photo,"pending-photo"));if(l)r.setLocalSignaturePath(store(local,"pending-local-signature"));if(f)r.setForeignSignaturePath(store(foreign,"pending-foreign-signature"));requests.saveAndFlush(r);audit.record(username,"EMPLOYEE_MEDIA_SUBMIT","EMPLOYEE_MEDIA_REQUEST",String.valueOf(r.getId()),null,"SUCCESS",null,"PENDING_DGM","photo="+p+",local="+l+",foreign="+f);}
 @Transactional(readOnly=true)public List<EmployeeMediaRequest> pending(String level){return requests.findByStatusOrderBySubmittedAtAsc("PENDING_"+level.toUpperCase(Locale.ROOT));}
 @Transactional public void decide(Long id,String level,String action,String remarks,String username){String lv=level.toUpperCase(Locale.ROOT),act=action.toUpperCase(Locale.ROOT);access.require(username,"APPROVE_"+lv);if(!access.hasAnyRole(username,lv,"ADMIN"))throw new AccessDeniedException("Wrong approval level");EmployeeMediaRequest r=requests.findById(id).orElseThrow(()->new IllegalArgumentException("Media request not found"));if(!r.getStatus().equals("PENDING_"+lv))throw new IllegalStateException("Request is not awaiting "+lv);if("REJECT".equals(act)&&(remarks==null||remarks.isBlank()))throw new IllegalArgumentException("Rejection remarks are required");User actor=users.findByUsername(username).orElseThrow();LocalDateTime now=LocalDateTime.now();if("DGM".equals(lv)){r.setDgmApprover(actor);r.setDgmDecidedAt(now);r.setDgmRemarks(clean(remarks));}else{r.setGmApprover(actor);r.setGmDecidedAt(now);r.setGmRemarks(clean(remarks));}if("REJECT".equals(act)){r.setStatus("REJECTED");r.setRejectionRemarks(remarks.trim());}else if("DGM".equals(lv))r.setStatus("PENDING_GM");else activate(r,actor);audit.record(username,"EMPLOYEE_MEDIA_"+lv+"_"+act,"EMPLOYEE_MEDIA_REQUEST",id.toString(),null,"SUCCESS",null,r.getStatus(),remarks);}
 private void activate(EmployeeMediaRequest r,User gm){Employee e=r.getEmployee();if(r.getPhotoPath()!=null)e.setPhotoPath(files.organizeEmployeeImage(r.getPhotoPath(),"profile",e.getId()));if(r.getLocalSignaturePath()!=null){String path=files.organizeEmployeeImage(r.getLocalSignaturePath(),"signature",e.getId());e.setSignaturePath(path);saveSignature(e,"LOCAL",path,r.getSubmittedBy(),gm);}if(r.getForeignSignaturePath()!=null){String path=files.organizeEmployeeImage(r.getForeignSignaturePath(),"foreign-signature",e.getId());e.setForeignSignaturePath(path);saveSignature(e,"FOREIGN",path,r.getSubmittedBy(),gm);}EmployeeMediaVersion mv=new EmployeeMediaVersion();mv.setEmployee(e);mv.setVersionNumber((int)mediaVersions.countByEmployeeId(e.getId())+1);mv.setPhotoPath(e.getPhotoPath());mv.setSignaturePath(e.getSignaturePath());mv.setForeignSignaturePath(e.getForeignSignaturePath());mediaVersions.save(mv);r.setStatus("APPROVED");}
 private void saveSignature(Employee e,String type,String path,User submitter,User gm){signatures.clearCurrent(e.getEmployeeNumber(),type);SignatureVersion v=new SignatureVersion();v.setEmployee(e);v.setEmployeeNumber(e.getEmployeeNumber());v.setSignatureType(type);v.setVersionNumber((int)signatures.countByEmployeeNumberAndSignatureType(e.getEmployeeNumber(),type)+1);v.setFilePath(path);v.setSubmittedBy(submitter);v.setDgmApprover(gm);v.setDgmDecidedAt(LocalDateTime.now());v.setGmApprover(gm);v.setGmDecidedAt(LocalDateTime.now());v.setStatus("APPROVED");v.setCurrentApproved(true);signatures.save(v);}
 private String store(MultipartFile f,String folder){files.validateImage(f);return files.storeImage(f,folder);}private boolean present(MultipartFile f){return f!=null&&!f.isEmpty();}private String clean(String v){return v==null?null:v.trim();}
}
