package com.bank.signaturemanagement.service;
import com.bank.signaturemanagement.entity.*; import com.bank.signaturemanagement.repository.*; import tools.jackson.core.JacksonException; import tools.jackson.databind.ObjectMapper; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.LinkedHashMap;
@Service public class EmployeeVersionService{
 private final EmployeeVersionRepository versions; private final UserRepository users; private final ObjectMapper json;
 public EmployeeVersionService(EmployeeVersionRepository versions,UserRepository users,ObjectMapper json){this.versions=versions;this.users=users;this.json=json;}
 @Transactional public EmployeeVersion append(Employee employee,String actor,String reason){EmployeeVersion v=new EmployeeVersion();v.setEmployee(employee);v.setVersionNo(versions.maxVersion(employee.getId())+1);v.setChangedBy(users.findByUsername(actor).orElse(null));v.setReason(reason);v.setSnapshotJson(snapshot(employee));return versions.save(v);}
 @Transactional public EmployeeVersion ensureBaseline(Employee employee,String actor,String reason){if(versions.maxVersion(employee.getId())>0)return null;return append(employee,actor,reason);}
 public String snapshot(Employee e){var m=new LinkedHashMap<String,Object>();m.put("employeeNumber",e.getEmployeeNumber());m.put("fullName",e.getFullName());m.put("designation",e.getDesignation()==null?null:e.getDesignation().getDesignationName());m.put("department",e.getDepartment()==null?null:e.getDepartment().getDepartmentName());m.put("branch",e.getBranch()==null?null:e.getBranch().getBranchName());m.put("status",e.getEmployeeStatus()==null?null:e.getEmployeeStatus().getStatusName());m.put("classification",e.getClassification());m.put("joiningDate",e.getJoiningDate());m.put("photoPath",e.getPhotoPath());m.put("localSignaturePath",e.getSignaturePath());m.put("foreignSignaturePath",e.getForeignSignaturePath());m.put("active",e.isActive());try{return json.writeValueAsString(m);}catch(JacksonException ex){throw new IllegalStateException("Could not serialize employee version",ex);}}
}
