package com.bank.signaturemanagement.service;

import com.bank.signaturemanagement.entity.*; import com.bank.signaturemanagement.repository.*;
import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
import java.time.LocalDateTime; import java.time.Year; import java.util.*; import java.util.regex.*;

@Service public class SignatureWorkflowService {
 public record Preview(SignatureUploadBatch batch,List<SignatureVersion> matched,List<String> errors){}
 private static final Pattern FILE=Pattern.compile("^(\\d{6})[_-](LOCAL|FOREIGN)(?:[_-].*)?\\.[A-Za-z0-9]+$",Pattern.CASE_INSENSITIVE);
 private final SignatureVersionRepository versions; private final SignatureUploadBatchRepository batches; private final EmployeeRepository employees; private final UserRepository users; private final FileStorageService files; private final AccessControlService access; private final AuditService audit; private final SignatureChangeProposalService changes;
 public SignatureWorkflowService(SignatureVersionRepository v,SignatureUploadBatchRepository b,EmployeeRepository e,UserRepository u,FileStorageService f,AccessControlService a,AuditService audit,SignatureChangeProposalService changes){versions=v;batches=b;employees=e;users=u;files=f;access=a;this.audit=audit;this.changes=changes;}

 @Transactional public SignatureVersion submit(Long employeeId,String type,MultipartFile file,String username){return submit(employeeId,type,file,username,null);}
 @Transactional public SignatureVersion submit(Long employeeId,String requestedType,MultipartFile file,String username,Long proposalId){requirePd(username);Employee e=employees.findById(employeeId).orElseThrow(()->new IllegalArgumentException("Employee not found"));if(!e.isActive())throw new IllegalArgumentException("Employee is not active");String type=normalize(requestedType);if(versions.existsByEmployeeNumberAndSignatureTypeAndStatusIn(e.getEmployeeNumber(),type,List.of("PENDING_DGM","PENDING_GM")))throw new IllegalArgumentException("This signature type already has a pending approval request");SignatureChangeProposal proposal=null;if(changes.has(e,type)){if(proposalId==null)throw new IllegalArgumentException("DGM or GM must initiate replacement of an existing "+type+" signature");proposal=changes.requireForUpload(proposalId,employeeId,type,username);}else if(proposalId!=null)throw new IllegalArgumentException("No initiation request is needed for a missing signature");SignatureVersion v=newVersion(e,type,file,username,null,"PENDING_DGM");v.setChangeProposal(proposal);if(proposal!=null)changes.markSubmitted(proposal,v);audit.record(username,proposal==null?"SIGNATURE_SUBMIT":"SIGNATURE_REPLACEMENT_SUBMIT","SIGNATURE_VERSION",String.valueOf(v.getId()),null,"SUCCESS",null,v.getStatus(),e.getEmployeeNumber()+" "+v.getSignatureType());return v;}
 @Transactional public Preview preview(MultipartFile[] uploadFiles,String username){requirePd(username);SignatureUploadBatch batch=new SignatureUploadBatch();batch.setBatchNumber("SIG-"+Year.now().getValue()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());batch.setSubmittedBy(user(username));batch.setStatus("DRAFT");batches.saveAndFlush(batch);List<SignatureVersion> matched=new ArrayList<>();List<String> errors=new ArrayList<>();for(MultipartFile file:uploadFiles==null?new MultipartFile[0]:uploadFiles){batch.setTotalFiles(batch.getTotalFiles()+1);String name=file.getOriginalFilename()==null?"":file.getOriginalFilename();Matcher m=FILE.matcher(name);if(!m.matches()){errors.add(name+": expected 123456_LOCAL.ext or 123456_FOREIGN.ext");continue;}Optional<Employee> employee=employees.findByEmployeeNumber(m.group(1));if(employee.isEmpty()||!employee.get().isActive()){errors.add(name+": no active employee match");continue;}try{String matchedType=normalize(m.group(2));if(changes.has(employee.get(),matchedType))throw new IllegalArgumentException("existing "+matchedType+" signature requires DGM/GM initiation and individual upload");matched.add(newVersion(employee.get(),matchedType,file,username,batch,"DRAFT"));}catch(IllegalArgumentException ex){errors.add(name+": "+ex.getMessage());}}
 batch.setMatchedFiles(matched.size());batch.setInvalidFiles(errors.size());batches.save(batch);audit.record(username,"SIGNATURE_BATCH_PREVIEW","SIGNATURE_UPLOAD_BATCH",batch.getId().toString(),null,"SUCCESS",null,"matched="+matched.size(),"invalid="+errors.size());return new Preview(batch,matched,errors);}
 @Transactional public void submitBatch(Long batchId,String username){requirePd(username);SignatureUploadBatch b=batches.findById(batchId).orElseThrow(()->new IllegalArgumentException("Signature batch not found"));if(!b.getSubmittedBy().getUsername().equals(username)&&!isAdmin(username))throw new AccessDeniedException("This is another user's batch");if(!"DRAFT".equals(b.getStatus()))throw new IllegalStateException("Batch has already been submitted");if(b.getInvalidFiles()>0)throw new IllegalArgumentException("Correct all unmatched or invalid files before submission");List<SignatureVersion> rows=versions.findAll().stream().filter(v->v.getBatch()!=null&&v.getBatch().getId().equals(batchId)).toList();if(rows.isEmpty())throw new IllegalArgumentException("No matched signature files");rows.forEach(v->v.setStatus("PENDING_DGM"));b.setStatus("PENDING_DGM");audit.record(username,"SIGNATURE_BATCH_SUBMIT","SIGNATURE_UPLOAD_BATCH",batchId.toString(),null,"SUCCESS","DRAFT","PENDING_DGM",null);}
 @Transactional(readOnly=true) public List<SignatureVersion> pending(String level){return versions.findByStatusOrderBySubmittedAtAsc("PENDING_"+level.toUpperCase(Locale.ROOT));}
 @Transactional(readOnly=true) public List<SignatureVersion> pendingForPd(){List<SignatureVersion> result=new ArrayList<>();result.addAll(versions.findByStatusOrderBySubmittedAtAsc("PENDING_DGM"));result.addAll(versions.findByStatusOrderBySubmittedAtAsc("PENDING_GM"));return result;}
 @Transactional(readOnly=true) public List<SignatureVersion> history(String employeeNumber){return versions.findByEmployeeNumberOrderBySignatureTypeAscVersionNumberDesc(employeeNumber);}
 @Transactional(readOnly=true) public Optional<SignatureVersion> current(String employeeNumber,String type){return versions.findByEmployeeNumberAndSignatureTypeAndCurrentApprovedTrue(employeeNumber,normalize(type));}
 @Transactional public void decide(Long id,String level,String action,String remarks,String username){String l=level.toUpperCase(Locale.ROOT),a=action.toUpperCase(Locale.ROOT);if(!Set.of("DGM","GM").contains(l)||!Set.of("APPROVE","REJECT").contains(a))throw new IllegalArgumentException("Invalid decision");access.require(username,"APPROVE_"+l);if(!access.hasAnyRole(username,l,"ADMIN"))throw new AccessDeniedException("Wrong approval level");SignatureVersion v=versions.findById(id).orElseThrow(()->new IllegalArgumentException("Signature request not found"));if(!v.getStatus().equals("PENDING_"+l))throw new IllegalStateException("Signature is not awaiting "+l);if("REJECT".equals(a)&&(remarks==null||remarks.isBlank()))throw new IllegalArgumentException("Rejection remarks are required");User actor=user(username);LocalDateTime now=LocalDateTime.now();if("DGM".equals(l)){v.setDgmApprover(actor);v.setDgmDecidedAt(now);v.setDgmRemarks(clean(remarks));}else{v.setGmApprover(actor);v.setGmDecidedAt(now);v.setGmRemarks(clean(remarks));}if("REJECT".equals(a)){v.setStatus("REJECTED");v.setRejectionRemarks(remarks.trim());}else if("DGM".equals(l))v.setStatus("PENDING_GM");else activate(v);changes.syncDecision(v);audit.record(username,"SIGNATURE_"+l+"_"+a,"SIGNATURE_VERSION",id.toString(),null,"SUCCESS",null,v.getStatus(),remarks);}
 @Transactional public void decideBatch(Long batchId,String level,String action,String remarks,Set<Long> rejectIds,String username){List<SignatureVersion> rows=versions.findAll().stream().filter(v->v.getBatch()!=null&&v.getBatch().getId().equals(batchId)&&v.getStatus().equals("PENDING_"+level.toUpperCase(Locale.ROOT))).toList();if(rows.isEmpty())throw new IllegalArgumentException("No pending rows in this batch");for(SignatureVersion row:rows)decide(row.getId(),level,rejectIds!=null&&rejectIds.contains(row.getId())?"REJECT":action,remarks,username);SignatureUploadBatch b=batches.findById(batchId).orElseThrow();b.setStatus(rows.stream().anyMatch(v->"PENDING_GM".equals(v.getStatus()))?"PENDING_GM":"DECIDED");}
 private void activate(SignatureVersion v){Employee e=v.getEmployee();String organized=files.organizeEmployeeImage(v.getFilePath(),v.getSignatureType().equals("LOCAL")?"signature":"foreign-signature",e.getId());v.setFilePath(organized);versions.clearCurrent(v.getEmployeeNumber(),v.getSignatureType());v.setCurrentApproved(true);v.setStatus("APPROVED");if("LOCAL".equals(v.getSignatureType()))e.setSignaturePath(organized);else e.setForeignSignaturePath(organized);}
 private SignatureVersion newVersion(Employee e,String type,MultipartFile file,String username,SignatureUploadBatch batch,String status){String t=normalize(type);files.validateImage(file);SignatureVersion v=new SignatureVersion();v.setEmployee(e);v.setEmployeeNumber(e.getEmployeeNumber());v.setSignatureType(t);v.setVersionNumber((int)versions.countByEmployeeNumberAndSignatureType(e.getEmployeeNumber(),t)+1);v.setFilePath(files.storeImage(file,"pending-"+t.toLowerCase(Locale.ROOT)+"-signature"));v.setSubmittedBy(user(username));v.setBatch(batch);v.setStatus(status);return versions.saveAndFlush(v);}
 private String normalize(String type){String t=type==null?"":type.trim().toUpperCase(Locale.ROOT);if(!Set.of("LOCAL","FOREIGN").contains(t))throw new IllegalArgumentException("Signature type must be LOCAL or FOREIGN");return t;} private User user(String n){return users.findByUsername(n).orElseThrow(()->new IllegalArgumentException("User not found"));} private void requirePd(String n){if(!access.hasAnyRole(n,"PD","ADMIN"))throw new AccessDeniedException("PD authority is required");} private boolean isAdmin(String n){return access.hasAnyRole(n,"ADMIN");} private String clean(String s){return s==null?null:s.trim();}
}
