package com.bank.signaturemanagement.service;

import com.bank.signaturemanagement.entity.*; import com.bank.signaturemanagement.repository.*; import com.lowagie.text.*; import com.lowagie.text.pdf.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.io.*; import java.nio.file.*; import java.security.MessageDigest; import java.time.*; import java.util.*; import java.util.List;

@Service public class SignatureBookService{
 private final SignatureBookRepository books;private final SignatureBookEntryRepository entries;private final SignatureBookAccessRepository grants;private final EmployeeRepository employees;private final UserRepository users;private final RoleRepository roles;private final AccessControlService access;private final AuditService audit;private final FileStorageService media;private final Path root;
 public SignatureBookService(SignatureBookRepository b,SignatureBookEntryRepository e,SignatureBookAccessRepository g,EmployeeRepository employees,UserRepository users,RoleRepository roles,AccessControlService access,AuditService audit,FileStorageService media,@Value("${app.signature-book.root}")String root){books=b;entries=e;grants=g;this.employees=employees;this.users=users;this.roles=roles;this.access=access;this.audit=audit;this.media=media;this.root=Path.of(root).toAbsolutePath().normalize();}
 @Transactional public SignatureBook generate(int year,String requestedType,String username){access.require(username,"BOOK_GENERATE");String type=type(requestedType);if(year<1900||year>Year.now().getValue()+1)throw new IllegalArgumentException("Invalid book year");User actor=users.findByUsername(username).orElseThrow();int version=books.maxVersion(year,type)+1;String number="SIGNATURE-BOOK-"+year+"-"+type+"-V"+version;List<Employee> included=employees.findAll().stream().filter(Employee::isActive).filter(e->e.getJoiningDate()==null||!e.getJoiningDate().isAfter(LocalDate.of(year,12,31))).filter(e->hasRequestedSignature(e,type)).sorted(Comparator.comparingInt((Employee e)->e.getDesignation()==null?Integer.MAX_VALUE:e.getDesignation().getHierarchyOrder()).thenComparing(e->e.getJoiningDate()==null?LocalDate.MAX:e.getJoiningDate()).thenComparing(Employee::getEmployeeNumber)).toList();if(included.isEmpty())throw new IllegalArgumentException("No employees with the selected signature type are eligible");try{Files.createDirectories(root);Path output=root.resolve(number+".pdf").normalize();requireRoot(output);writePdf(output,included,type,year,version);SignatureBook book=new SignatureBook();book.setBookNumber(number);book.setBookYear(year);book.setVersionNo(version);book.setSignatureType(type);book.setFilePath(output.getFileName().toString());book.setFileSha256(hash(output));book.setGeneratedBy(actor);books.saveAndFlush(book);int serial=1;for(Employee employee:included){if((type.equals("LOCAL")||type.equals("BOTH"))&&employee.getSignaturePath()!=null)saveEntry(book,employee,serial,"LOCAL",employee.getSignaturePath());if((type.equals("FOREIGN")||type.equals("BOTH"))&&employee.getForeignSignaturePath()!=null)saveEntry(book,employee,serial,"FOREIGN",employee.getForeignSignaturePath());serial++;}audit.record(username,"BOOK_GENERATE","SIGNATURE_BOOK",String.valueOf(book.getId()),null,"SUCCESS",null,number,"entries="+included.size());return book;}catch(IOException|DocumentException ex){throw new IllegalStateException("Could not generate signature book",ex);}}
 @Transactional(readOnly=true)public List<SignatureBook> visible(String username){return books.findAllByOrderByGeneratedAtDesc().stream().filter(SignatureBook::isActive).filter(b->canAccess(b,username)).toList();}
 @Transactional(readOnly=true)public SignatureBook requireBook(Long id,String username){SignatureBook b=books.findById(id).orElseThrow(()->new IllegalArgumentException("Book not found"));if(!b.isActive()||!canAccess(b,username))throw new AccessDeniedException("You do not have access to this signature book");return b;}
 @Transactional(readOnly=true)public Path content(Long id,String username){SignatureBook b=requireBook(id,username);Path p=root.resolve(b.getFilePath()).normalize();requireRoot(p);if(!Files.isRegularFile(p))throw new IllegalStateException("Stored PDF is missing");try{if(b.getFileSha256()!=null&&!b.getFileSha256().equals(hash(p)))throw new IllegalStateException("Stored PDF integrity check failed");}catch(IOException e){throw new IllegalStateException(e);}return p;}
 @Transactional public void grant(Long bookId,Long userId,Long roleId,boolean enabled,String admin){access.require(admin,"BOOK_ACCESS_MANAGE");if((userId==null)==(roleId==null))throw new IllegalArgumentException("Select exactly one user or role");SignatureBook b=books.findById(bookId).orElseThrow();SignatureBookAccess a=userId!=null?grants.findByBookIdAndUserId(bookId,userId).orElseGet(SignatureBookAccess::new):grants.findByBookIdAndRoleId(bookId,roleId).orElseGet(SignatureBookAccess::new);a.setBook(b);a.setUser(userId==null?null:users.findById(userId).orElseThrow());a.setRole(roleId==null?null:roles.findById(roleId).orElseThrow());a.setGrantedBy(users.findByUsername(admin).orElseThrow());a.setActive(enabled);grants.save(a);audit.record(admin,"BOOK_ACCESS_CHANGE","SIGNATURE_BOOK",bookId.toString(),null,"SUCCESS",null,"enabled="+enabled,"user="+userId+",role="+roleId);}
 @Transactional public void deactivate(Long id,String admin){access.require(admin,"BOOK_ACCESS_MANAGE");SignatureBook b=books.findById(id).orElseThrow();b.setActive(false);audit.record(admin,"BOOK_DEACTIVATE","SIGNATURE_BOOK",id.toString(),null,"SUCCESS","active","inactive",null);}
 @Transactional(readOnly=true)public List<SignatureBookAccess> grants(Long id,String username){access.require(username,"BOOK_ACCESS_MANAGE");books.findById(id).orElseThrow(()->new IllegalArgumentException("Book not found"));return grants.findByBookIdOrderByGrantedAtDesc(id);}
 private boolean canAccess(SignatureBook b,String username){User u=users.findByUsername(username).orElse(null);return u!=null&&u.isActive()&&u.getRole()!=null&&u.getRole().isActive();}
 private boolean hasRequestedSignature(Employee e,String type){String c=e.getClassification()==null?"BOTH":e.getClassification();boolean local=(c.equals("LOCAL")||c.equals("BOTH"))&&e.getSignaturePath()!=null&&!e.getSignaturePath().isBlank();boolean foreign=(c.equals("FOREIGN")||c.equals("BOTH"))&&e.getForeignSignaturePath()!=null&&!e.getForeignSignaturePath().isBlank();return type.equals("LOCAL")?local:type.equals("FOREIGN")?foreign:local||foreign;}
 private void saveEntry(SignatureBook b,Employee e,int serial,String type,String path){SignatureBookEntry entry=new SignatureBookEntry();entry.setBook(b);entry.setEmployee(e);entry.setSerialNumber(serial);entry.setSignatureType(type);entry.setSignaturePath(path);entries.save(entry);}
 private void writePdf(Path output,List<Employee> list,String type,int year,int version)throws IOException,DocumentException{try(OutputStream out=Files.newOutputStream(output,StandardOpenOption.CREATE_NEW)){Document d=new Document(PageSize.A4.rotate(),24,24,24,24);PdfWriter.getInstance(d,out);d.open();Paragraph title=new Paragraph("Signature Book "+year+" v"+version,new Font(Font.HELVETICA,18,Font.BOLD));title.setAlignment(Element.ALIGN_CENTER);d.add(title);d.add(new Paragraph("Type: "+type));int cols=type.equals("BOTH")?7:6;PdfPTable t=new PdfPTable(cols);t.setWidthPercentage(100);for(String h:(type.equals("BOTH")?List.of("SL","Employee ID","Name","Designation","Joining Date","Local","Foreign"):List.of("SL","Employee ID","Name","Designation","Joining Date","Signature")))header(t,h);int n=1;for(Employee e:list){text(t,String.valueOf(n++));text(t,e.getEmployeeNumber());text(t,e.getFullName());text(t,e.getDesignation()==null?"":e.getDesignation().getDesignationName());text(t,String.valueOf(e.getJoiningDate()));if(type.equals("BOTH")){image(t,e.getSignaturePath());image(t,e.getForeignSignaturePath());}else image(t,type.equals("LOCAL")?e.getSignaturePath():e.getForeignSignaturePath());}d.add(t);d.close();}}
 private void header(PdfPTable t,String s){PdfPCell c=new PdfPCell(new Phrase(s,new Font(Font.HELVETICA,10,Font.BOLD)));c.setPadding(5);t.addCell(c);}private void text(PdfPTable t,String s){PdfPCell c=new PdfPCell(new Phrase(s==null?"":s,new Font(Font.HELVETICA,9)));c.setPadding(5);t.addCell(c);}private void image(PdfPTable t,String stored){PdfPCell c=new PdfPCell();c.setPadding(4);if(stored!=null)try{Path p=media.resolveForRead(stored);if(Files.isRegularFile(p)){Image i=Image.getInstance(p.toString());i.scaleToFit(120,45);c.addElement(i);}}catch(Exception ignored){}t.addCell(c);}
 private String type(String v){String s=v==null?"":v.toUpperCase(Locale.ROOT);if(!Set.of("LOCAL","FOREIGN","BOTH").contains(s))throw new IllegalArgumentException("Invalid signature-book type");return s;}private void requireRoot(Path p){if(!p.startsWith(root))throw new IllegalArgumentException("Invalid book path");}private String hash(Path p)throws IOException{try{byte[] digest=MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(p));return java.util.HexFormat.of().formatHex(digest);}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
