package com.bank.signaturemanagement.service;
import com.bank.signaturemanagement.entity.*; import com.bank.signaturemanagement.repository.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class SignatureChangeProposalService {
 private static final List<String> OPEN=List.of("PD_ACTION_REQUIRED","PENDING_DGM","PENDING_GM");
 private final SignatureChangeProposalRepository proposals;private final EmployeeRepository employees;private final UserRepository users;private final AccessControlService access;private final AuditService audit;
 public SignatureChangeProposalService(SignatureChangeProposalRepository p,EmployeeRepository e,UserRepository u,AccessControlService a,AuditService audit){proposals=p;employees=e;users=u;access=a;this.audit=audit;}
 @Transactional public void initiate(Long employeeId,String requestedType,String remarks,String username){if(!access.hasAnyRole(username,"DGM","GM","ADMIN"))throw new AccessDeniedException("Only DGM or GM may initiate a signature replacement");String type=type(requestedType);if(remarks==null||remarks.isBlank())throw new IllegalArgumentException("Initiator remarks are required");Employee employee=employees.findById(employeeId).orElseThrow(()->new IllegalArgumentException("Employee not found"));if(!employee.isActive())throw new IllegalArgumentException("Employee is inactive");if(!has(employee,type))throw new IllegalArgumentException("This signature type is missing; PD can upload it directly without an initiation request");if(proposals.existsByEmployeeIdAndSignatureTypeAndStatusIn(employeeId,type,OPEN))throw new IllegalArgumentException("An open replacement request already exists for this signature type");SignatureChangeProposal p=new SignatureChangeProposal();p.setEmployee(employee);p.setSignatureType(type);p.setInitiatedBy(users.findByUsername(username).orElseThrow());p.setInitiatorRemarks(remarks.trim());proposals.saveAndFlush(p);audit.record(username,"SIGNATURE_CHANGE_INITIATE","SIGNATURE_CHANGE_PROPOSAL",String.valueOf(p.getId()),null,"SUCCESS",null,"PD_ACTION_REQUIRED",employee.getEmployeeNumber()+" "+type+": "+remarks.trim());}
 @Transactional(readOnly=true) public List<SignatureChangeProposal> pendingPd(String username){if(!access.hasAnyRole(username,"PD","ADMIN"))throw new AccessDeniedException("PD authority is required");return proposals.findByStatusOrderByCreatedAtAsc("PD_ACTION_REQUIRED");}
 @Transactional public SignatureChangeProposal requireForUpload(Long id,Long employeeId,String requestedType,String username){if(!access.hasAnyRole(username,"PD","ADMIN"))throw new AccessDeniedException("PD authority is required");SignatureChangeProposal p=proposals.findById(id).orElseThrow(()->new IllegalArgumentException("Replacement request not found"));if(!"PD_ACTION_REQUIRED".equals(p.getStatus()))throw new IllegalStateException("Replacement request is no longer awaiting PD");if(!p.getEmployee().getId().equals(employeeId)||!p.getSignatureType().equals(type(requestedType)))throw new IllegalArgumentException("Replacement request does not match the employee and signature type");return p;}
 @Transactional public void markSubmitted(SignatureChangeProposal p,SignatureVersion v){p.setSubmittedVersion(v);p.setStatus("PENDING_DGM");}
 @Transactional public void syncDecision(SignatureVersion v){SignatureChangeProposal p=v.getChangeProposal();if(p==null)return;p.setStatus(switch(v.getStatus()){case "PENDING_GM"->"PENDING_GM";case "APPROVED"->"EFFECTIVE";case "REJECTED"->"REJECTED";default->p.getStatus();});}
 public boolean has(Employee e,String type){return "LOCAL".equals(type)?e.getSignaturePath()!=null&&!e.getSignaturePath().isBlank():e.getForeignSignaturePath()!=null&&!e.getForeignSignaturePath().isBlank();}
 public String type(String value){String v=value==null?"":value.trim().toUpperCase(Locale.ROOT);if(!Set.of("LOCAL","FOREIGN").contains(v))throw new IllegalArgumentException("Signature type must be LOCAL or FOREIGN");return v;}
}
