package com.bank.signaturemanagement.controller;
import com.bank.signaturemanagement.service.*; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.servlet.mvc.support.RedirectAttributes; import java.util.*;
@Controller public class SignatureWorkflowController {
 private final SignatureWorkflowService service;private final EmployeeService employees;private final SignatureChangeProposalService changes;private final EmployeeMediaRequestService mediaRequests; public SignatureWorkflowController(SignatureWorkflowService s,EmployeeService employees,SignatureChangeProposalService changes,EmployeeMediaRequestService mediaRequests){service=s;this.employees=employees;this.changes=changes;this.mediaRequests=mediaRequests;}
 @GetMapping("/pd/signatures") public String pd(@RequestParam(defaultValue="")String query,@RequestParam(defaultValue="0")int page,Authentication a,Model m){var employeePage=employees.search(query,page);Map<String,String> pending=new HashMap<>();for(var version:service.pendingForPd())pending.put(version.getEmployeeNumber()+":"+version.getSignatureType(),version.getStatus());Map<Long,String> mediaPending=new HashMap<>();for(var request:mediaRequests.pending("DGM"))mediaPending.put(request.getEmployee().getId(),"PENDING_DGM");for(var request:mediaRequests.pending("GM"))mediaPending.put(request.getEmployee().getId(),"PENDING_GM");List<PdSignatureRow> rows=employeePage.getContent().stream().map(e->new PdSignatureRow(e,pending.get(e.getEmployeeNumber()+":LOCAL"),pending.get(e.getEmployeeNumber()+":FOREIGN"),mediaPending.get(e.getId()))).filter(PdSignatureRow::actionable).toList();m.addAttribute("query",query);m.addAttribute("employeeRows",rows);m.addAttribute("replacementRequests",changes.pendingPd(a.getName()));return "pd/signature-upload";}
 @PostMapping("/pd/employees/{id}/signatures") public String upload(@PathVariable Long id,@RequestParam String type,@RequestParam(required=false)Long proposalId,@RequestParam MultipartFile file,Authentication a,RedirectAttributes r){try{service.submit(id,type,file,a.getName(),proposalId);r.addFlashAttribute("success","Signature submitted to DGM");}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/pd/signatures";}
 @PostMapping("/pd/employees/{id}/media") public String uploadMedia(@PathVariable Long id,@RequestParam(required=false)MultipartFile photo,@RequestParam(required=false)MultipartFile localSignature,@RequestParam(required=false)MultipartFile foreignSignature,Authentication a,RedirectAttributes r){try{mediaRequests.submit(id,photo,localSignature,foreignSignature,a.getName());r.addFlashAttribute("success","Employee media submitted to DGM");}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/pd/signatures";}
 @PostMapping("/pd/signatures/bulk/preview") public String preview(@RequestParam("files") MultipartFile[] files,Authentication a,Model m){var p=service.preview(files,a.getName());m.addAttribute("preview",p);return "pd/signature-bulk-preview";}
 @PostMapping("/pd/signatures/bulk/{id}/submit") public String submitBatch(@PathVariable Long id,Authentication a,RedirectAttributes r){try{service.submitBatch(id,a.getName());r.addFlashAttribute("success","Signature batch submitted to DGM");}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/pd/signatures";}
 @PostMapping("/{level:dgm|gm}/signature-requests/{id}/decision") public String decide(@PathVariable String level,@PathVariable Long id,@RequestParam String action,@RequestParam(required=false)String remarks,Authentication a,RedirectAttributes r){try{service.decide(id,level,action,remarks,a.getName());r.addFlashAttribute("success","Signature decision saved");}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/"+level+"/dashboard";}
 @PostMapping("/{level:dgm|gm}/media-requests/{id}/decision") public String decideMedia(@PathVariable String level,@PathVariable Long id,@RequestParam String action,@RequestParam(required=false)String remarks,Authentication a,RedirectAttributes r){try{mediaRequests.decide(id,level,action,remarks,a.getName());r.addFlashAttribute("success","Media decision saved");}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/"+level+"/dashboard";}
 @GetMapping("/{level:dgm|gm}/signature-requests") public String inbox(@PathVariable String level,Model m){m.addAttribute("level",level.toUpperCase());m.addAttribute("requests",service.pending(level));return "signature-approvals";}
 @GetMapping("/{level:dgm|gm}/signature-management") public String management(@PathVariable String level,@RequestParam(defaultValue="")String query,@RequestParam(defaultValue="0")int page,Model m){m.addAttribute("level",level.toUpperCase());m.addAttribute("query",query);m.addAttribute("employees",employees.search(query,page));return "signature-management";}
 @PostMapping("/{level:dgm|gm}/employees/{id}/signature-change") public String initiate(@PathVariable String level,@PathVariable Long id,@RequestParam String type,@RequestParam String remarks,Authentication a,RedirectAttributes r){try{changes.initiate(id,type,remarks,a.getName());r.addFlashAttribute("success",type+" signature replacement sent to PD");}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/"+level+"/signature-management";}
 public record PdSignatureRow(com.bank.signaturemanagement.entity.Employee employee,String localPending,String foreignPending,String mediaPending){public boolean actionable(){return employee.getPhotoPath()==null||employee.getSignaturePath()==null||employee.getForeignSignaturePath()==null||localPending!=null||foreignPending!=null||mediaPending!=null;}public String pendingLabel(String status){return status==null?null:status.replace("PENDING_","Pending ").replace('_',' ');}}
}
